# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx1024m -XX:+UseSerialGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1024m -XX:+UseSerialGC
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX & Jetpack settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin settings
kotlin.code.style=official
ksp.useKsp2=false
ksp.incremental=false
ksp.incremental.intermodule=false
